### ISSUE TITLE
Убрать обработку кнопки из класса энкодера

### ISSUE THREAD

**Issue by dr-dobermann** [AlexGyver/GyverLibs#10]
Алекс, привет.

Я не использую твою библиотеку, посколькуу меня немного другая модель приложения, но либа реально классная, в будущем обязательно найду ей применение.

Я в своем проекте использую одновременно кнопку и энкодер и, сначала, сделал также как и у тебя: контроль кнопки энкодера в классе энкодера, но потом пришел к выводу, что это простое дублирование кода (у тебя я вижу то же самое) и убрал функциональность кнопки из энкодера.
Думаю тебе тоже стоит это сделать, что сэкономит тебе и пользователям твоей библиотеки несколько драгоценных байт дорогой памяти микроконтроллера.

Тем более, что не все энкодеры идут с кнопкой.

Можно решить этот вопрос не меняя интерфейс класса енкодера, чтобы те пользователи библиотеки, которые уже используют его, не были вынуждены переписывать свой код.

**Comment by TesAnti** [comment]
Убирать поддержку кнопки нельзя. Это нарушает принцип обратной совместимости.
Но если прям так надо сэкономить байты, то лучше добавить дефайн, который эту поддержку исключает.
Кроме того, даже если у гайвера на это времени не будет, ты можешь добавить этот самый дефайн самостоятельно и сделать пул реквест.
