### ISSUE TITLE
Добавить бы метод проверки состояния в GTimer

### ISSUE THREAD

**Issue by atomoc** [AlexGyver/GyverLibs#15]
Часто использую таймеры как функцию setTimeout в js, только в данном случае приходится в мэйн функции останавливать таймер методом .stop(), и в момент нужного события, например if (button.isSingle()) запускать timer.setTimeout(ms); timer.start(); и в if (timer.isReady()) опять останавливать таймер. Не сказал бы, что прям очень удобно, но удобней пока не было придумано, а у самого пока от идеи только недовольство) В целом такой метод меня устраивает, но хотелось бы его усовершенствовать добавлением метода timer.isEnabled(). Сделай, пожалуйста.

**Comment by atomoc** [comment]
А вообще, моё недовольство легко бы решилось, если бы был убран метод start, а вместо него использовался setInterval и setTimeout. В методе  isReady тогда нужно сделать проверку на тип таймера (интервал или таймаут) и, если таймаут, запускать stop().

И ещё, непонятно, для чего reset()? Пробовал его использовать, но он вообще не работал, правда это было не знаю в какой версии, может ты и исправил его.

**Comment by AlexGyver** [comment]
Если честно, не понял вообще, что как зачем надо добавить. Может тебе стоит пересмотреть логику работы своего кода?
Ресет работает и работал всегда, он сбрасывает счётчик периода, т.е. если таймер стоит на 10 секунд, и с момента последнего срабатывания прошло 5 секунд и ты делаешь ресет, то таймер сработает через 10 секунд в следующий раз, очевидно

**Comment by atomoc** [comment]
Я по всякому пробовал проверять ресет, не буду углубляться в воспоминания, к тому же они зачастую меняются на физ уровне, может что то и упустил, а может сейчас вру.

Логику не надо будет пересматривать если оставить всё как есть.

Суть в том, что в js setTimeout и setInterval уже содержит в себе start, к этому все привыкли, почему бы здесь не сделать так же?

**Comment by AlexGyver** [comment]
Я не знаю кто и к чему привык, потому не понимаю вообще о чём идёт речь...

**Comment by atomoc** [comment]
будет не так: timer.setInterval(3000);... timer.start();.... timer.stop();... timer.start();
а так: int timerInterval = 3000;... timer.setInterval(timerInterval);... timer.stop();... timer.setInterval(timerInterval);

**Comment by AlexGyver** [comment]
И зачем, в каких ситуациях это использовать?

**Comment by atomoc** [comment]
И так: int timerInterval = 3000;... timer.setTimeout(timerInterval);... timer.stop();... timer.setInterval(timerInterval);

**Comment by atomoc** [comment]
В тех же самых. Просто меньше кода из-за отсутствия .start()

**Comment by AlexGyver** [comment]
Я так понял, что не хватает автоматического старта в setInterval? А в каких ситуациях нужно постоянно включать и выключать таймер?

**Comment by atomoc** [comment]
Важней не это, а именно setTimeout, вот это чудо из чудес ;-)

**Comment by atomoc** [comment]
Я уже третью программу без этого никак не могу обойтись

**Comment by AlexGyver** [comment]
Можно в таком случае все понятно и подробно расписать, что и как должно работать? Потому что я не понимаю зачем это нужно и зачем так использовать таймер

**Comment by atomoc** [comment]
![image](https://user-images.githubusercontent.com/465108/68632254-e6497700-04fe-11ea-9986-e9a3ed52872f.png)

**Comment by atomoc** [comment]
Попробую

**Comment by AlexGyver** [comment]
Таймаут - случаем не о ручном режиме таймера идёт речь? Здесь он называется так.

**Comment by atomoc** [comment]
О ручном всмысле не использовать tick()? В таком случае разве вообще что то будет работать?

**Comment by atomoc** [comment]
К тому же это непонятно для новичков. Проблем, согласен, добавление setTimeout может добавить в коде использующем старые версии, но это можно обойти установкой заглушки на метод start()

**Comment by AlexGyver** [comment]
> О ручном всмысле не использовать tick()? В таком случае разве вообще что то будет работать?

Ручной режим работы таймера

**Comment by atomoc** [comment]
setTimeout будет работать точно так же как и setInterval, пока время цикла не наступит. Как только время цикла наступит, сработает stop(), в чём и будет принципиальное отличие его от setInterval

**Comment by AlexGyver** [comment]
> К тому же это непонятно для новичков. Проблем, согласен, добавление setTimeout может добавить в коде использующем старые версии, но это можно обойти установкой заглушки на метод start()

Если честно все ещё не понимаю ничего. Добавить старт в setInterval - возможно стоит это сделать, да. Убирать старт - глупость, лично я часто пользуюсь остановкой таймера, и запуском его на тот же период

**Comment by AlexGyver** [comment]
> setTimeout будет работать точно так же как и setInterval, пока время цикла не наступит. Как только время цикла наступит, сработает stop(), в чём и будет принципиальное отличие его от setInterval

Это ручной режим таймера

**Comment by atomoc** [comment]
Нашёл

**Comment by atomoc** [comment]
Правда непонятно, я же видел твой пример и у меня почти получилось завести его в уме, прям тепло лампочки ощущал, но так и не смог понять

**Comment by atomoc** [comment]
Спасибо за разъяснение, конечно

**Comment by AlexGyver** [comment]
> setTimeout будет работать точно так же как и setInterval, пока время цикла не наступит. Как только время цикла наступит, сработает stop(), в чём и будет принципиальное отличие его от setInterval

При проверке на if .isReady выдаст тру только один раз, дальше будет возвращать фолс? Или до перезапуска тру?

**Comment by atomoc** [comment]
Да, только один раз. До перезапуска не надо

**Comment by AlexGyver** [comment]
Без проблем, давай допилим библиотеку под любителей js. Только мне нужно понять, что и как должно работать, и главное - зачем и где это использовать

**Comment by atomoc** [comment]
Могу переделать твой пример Manual. Принцип то идентичен

**Comment by AlexGyver** [comment]
Значит туду:
1. Добавить setInterval как синтаксический аналог setPeriod, чисто для привычности
2. setPeriod (setInterval) запускают таймер (также сбрасывая период, там внутри reset)
3. Добавить setTimeout - делает тож самое что интервал (перезапуск), но автоматически пкреключает режим таймера на ручной
Все верно?

**Comment by atomoc** [comment]
100%

**Comment by AlexGyver** [comment]
Оки, посплю чутка и утром уже выкачу апдейт

**Comment by atomoc** [comment]
Надо GyverButton добавить в пример GTimer_manual, либо типа того. Чтобы по нажатию на кнопку запускался setPeriod(3000) а уже в if (isReady()) выводилось: Serial.println("Timer!");

**Comment by AlexGyver** [comment]
Не понял. Опиши словами логику работы кода, без привязки к библиотекам. Чисто что как должно работать

**Comment by atomoc** [comment]
GyverButton может запутать тех, кто ещё до него не дошёл

**Comment by atomoc** [comment]
Я пытаюсь пример поправить и сделать ПР, примешь его потом, как допилишь код. Сам подумаю тогда, как пример лучше оформить.

**Comment by AlexGyver** [comment]
Да фиг с ним с примером, ты задачу опиши, какую нужно решить. Мне кажется что то ты не так делаешь просто

**Comment by atomoc** [comment]
Жмёшь на кнопку, запускается setTimeout(3000), после заданного интервала срабатывает true в isReady и никакого цикла далее не следует. Ты же вроде как понял

**Comment by atomoc** [comment]
Или нужно описать логику для общественности?

**Comment by atomoc** [comment]
По моему пример как раз таки и решит эту задачу

**Comment by AlexGyver** [comment]
Я понял чего не хватало для счастья, но зачем оно было - понял только сейчас. Я бы просто ввел ещё один бул флаг в основной программе) но да, с доработанной либой будет красивее

**Comment by atomoc** [comment]
https://www.arduino.cc/en/tutorial/button не хочется брать отсюда код для описания примера, по этому и завёл речь о GyverButton

**Comment by AlexGyver** [comment]
Да можно примеров с кнопками и таймерами много придумать)

**Comment by atomoc** [comment]
Если будет setTimeout буду ещё более очень очень признателен, да и вряд ли я один

**Comment by AlexGyver** [comment]
Сделаю, это ерунда. По доработке этой либы вообще ничего не просили ниразу

**Comment by atomoc** [comment]
Низкий поклон и наилучших пожеланий

**Comment by AlexGyver** [comment]
А isReady не трогать, само имя? А то не знаю как у вас там в js

**Comment by AlexGyver** [comment]
в общем выкатил 3.0, вообще всё переделал и оптимизировал, теперь это полноценный таймер со всеми плюшками =)

**Comment by atomoc** [comment]
Моему ликованию нет предела, спасибо просто огромнейшее, сейчас же перепишу везде у себя код!)

Добавь ещё, пожалуйста, isEnabled(), чтобы избежать создания переменных для отслеживания состояний таймеров.

**Comment by atomoc** [comment]
Или isRun()

**Comment by AlexGyver** [comment]
сделал

**Comment by atomoc** [comment]
Ты вообще спишь?!)

**Comment by AlexGyver** [comment]
Сегодня сбил режим сильно

**Comment by atomoc** [comment]
isReady() прерывает loop

**Comment by AlexGyver** [comment]
> isReady() прерывает loop

Библиотека не использует прерывания

**Comment by atomoc** [comment]
и вначале, если даже не задан таймаут, isReady срабатывает. То есть таймер, видимо, в режиме интервала запускается. Думаю, надо по setTimeout и setInterval лишь делать старт

**Comment by atomoc** [comment]
Хотя для поддержки кода со старым таймером выгодно оставить это для тех мест, где интервал больше 1, полагаю

**Comment by atomoc** [comment]
> Библиотека не использует прерывания

Постараюсь проверить вдоль и поперёк

**Comment by AlexGyver** [comment]
У меня абсолютно везде таймер как интервал используется с самого запуска. Но раз полностью изменилась реализация таймера, можно сделать его остановленным при создании объекта 
Про прерывает луп не понял

**Comment by AlexGyver** [comment]
> > Библиотека не использует прерывания
> 
> Постараюсь проверить вдоль и поперёк

Просто расшифруй что именно означает "прерывает loop"

**Comment by atomoc** [comment]
> можно сделать его остановленным при создании объекта

да, только оставить для тех мест, где задано время при создании экземпляра GTimer_ms timer(1000)

**Comment by AlexGyver** [comment]
> > можно сделать его остановленным при создании объекта
> 
> да, только оставить для тех мест, где задано время при создании экземпляра GTimer_ms timer(1000)

Таймер больше не создаётся таким образом

**Comment by atomoc** [comment]
Логично. Тогда придётся уповать на внимательность пользователей

**Comment by atomoc** [comment]
Или всегда делать timer.stop() в main

**Comment by AlexGyver** [comment]
Так что по прерыванию? В чем загвоздка

**Comment by atomoc** [comment]
Ща

**Comment by atomoc** [comment]
if (timerFan.isReady()) { реально глушит loop. Если не добавить timerFan.stop() в main

![image](https://user-images.githubusercontent.com/465108/68656141-4f061300-0542-11ea-8b9e-3658b1e84dec.png)

**Comment by atomoc** [comment]
В целом всё супер!

**Comment by AlexGyver** [comment]
Что значит глушит loop? На скриншоте непонятно ровно ничего

**Comment by atomoc** [comment]
Прерывает. Сори, я в начало loop добавил Serial.println(digitalRead(BUTTON_PIN));

**Comment by atomoc** [comment]
На скрине видно как доходит до 7 цикла и прерывается

**Comment by AlexGyver** [comment]
Нет, так мы точно не разберемся в чем проблема. Что конкретно происходит , чего не должно происходить?

**Comment by atomoc** [comment]
Мы это уже обсудили. Надо не запускать таймеры если не было инициализации setInterval и setTimeout

**Comment by atomoc** [comment]
Я не знаю с чем это может быть связано, попробую упростить пример

**Comment by AlexGyver** [comment]
> Мы это уже обсудили. Надо не запускать таймеры если не было инициализации setInterval и setTimeout

Обсудили автоматический запуск таймера. По прерыванию я всё ещё не понимаю в чем проблема, у меня все примеры работают корректно

**Comment by atomoc** [comment]
Попробуй такой:
```
#include "GyverTimer.h"

GTimer_ms timer;

void setup() {
  Serial.begin(9600);
  // timer.stop();
}

void loop() {
  Serial.println("1");  

  if (timer.isReady()) {
    
  }
}
```

**Comment by atomoc** [comment]
Может это какой то защитный механизм МК (pro mini 328p)

**Comment by AlexGyver** [comment]
Напишу ещё раз: таймер переписан заново, GTimer_ms уже не используется, открой примеры.
Данная конструкция вешает код, потому что интервал по умолчанию задан 0, ты никак его не меняешь, и внутри проверки получается бесконечный цикл. Потому что нельзя запускать таймер без указания периода

**Comment by atomoc** [comment]
Ну я то это понял. Надо, думаю, в обязательном порядке отключить автоматический запуск таймера

**Comment by AlexGyver** [comment]
раз понял, зачем использовать старую конструкцию в нештатном режиме? Автоматический запуск при указанном времени при создании я оставлю, потому что у меня лично на этом коде работают все прошивки. Проверю и выкачу версию 3.2, вот её тестируй тогда

**Comment by atomoc** [comment]
Что бы синхронизировать все линии понимания

**Comment by AlexGyver** [comment]
Щито?.....

**Comment by atomoc** [comment]
По данной теме, само собой)

**Comment by atomoc** [comment]
> Проверю и выкачу версию 3.2, вот её тестируй тогда

Ок

**Comment by atomoc** [comment]
Прости за мой русский, самого разбудили перфоратором за стеной

**Comment by AlexGyver** [comment]
У меня тоже пид@р какой то сверлит

**Comment by AlexGyver** [comment]
сделал 3.2. Старые классы _ms не используй, иначе запутаешься и вообще код работать не будет

**Comment by atomoc** [comment]
Круто! Проверил, всё ок

**Comment by atomoc** [comment]
Второй таймаут не отрабатывает
```
#include "GyverTimer.h"

GTimer timer;
GTimer timer2;

void setup() {
  Serial.begin(9600);
  timer.setTimeout(2000);
  // timer.stop();
}

void loop() {
  Serial.print(timer.isEnabled());
  Serial.print(" - ");
  Serial.println(timer2.isEnabled());

  if (timer.isReady()) {
    Serial.println(timer.isEnabled());
    delay(1000);

    timer2.setTimeout(2000);
  }
}
```
