### ISSUE TITLE
GyverButtons

### ISSUE THREAD

**Issue by x3mEr** [AlexGyver/GyverLibs#17]
Version: 2.14 (09-sep-2019)
Holding a button resets variable "last_counter", thereby reseting isSingle, isDouble, isTriple and other (last_counter).
Баг или фича: принцип работы библиотеки такой, что различные нажатия кнопок сбрасываются только после вызова опрашивающей функции (isClick, isHolded...).
Но isSingle, isDouble and isTriple и остальные (last_counter) можно сбросить, если удерживать кнопку (hold).
Баг бага или баг фичи: такой сброс последовательности нажатий удержанием кнопки не сбрасывает флаг counter_flag.

**Comment by AlexGyver** [comment]
Это интересно. Вообще это можно использовать как фичу для алгоритма клик-клик-удержание

**Comment by x3mEr** [comment]
Если исправить библиотеку, чтобы счётчик нажатий last_counter (вроде так, не помню уже) не сбрасывался в атрибуте isHolded, то её тоже можно будет использовать для такого алгоритма ;)
Но надо смотреть, что ещё такая правка может задеть.

**Comment by x3mEr** [comment]
*нажал мимо кнопки)

**Comment by AlexGyver** [comment]
Надо попробовать)

**Comment by AlexGyver** [comment]
выкатил 3.1 версию, посмотри пример clicks_step

**Comment by x3mEr** [comment]
Так и не скажешь. Вредо всё круто.
То, о чём писал я - исправлено)

В GyverButton.cpp в стороке 121 зачем нужно условие (millis() - btn_timer >= _step_timeout)?

**Comment by AlexGyver** [comment]
Затем что так работает "шаг", у него свой таймер

**Comment by x3mEr** [comment]
done!

**Comment by x3mEr** [comment]
> Затем что так работает "шаг", у него свой таймер

Понял. Свой определитель isHold.
