### ISSUE TITLE
Double, triple (and more) click is always set single click flag.

### ISSUE THREAD

**Issue by x3mEr** [AlexGyver/GyverLibs#18]
Version: 2.14 (09-sep-2019)
Double, triple (and more) click is always set single click flag.
Double, triple (and more) click always includes single click. For example, after double clicking both functions isDouble() and isClick() will return true.

Двойное и более нажатие всегда подразумевает и одинарное. Т. е. при, например, двойном нажатии кнопки, обе функции isClick() и isDouble() вернут true.

**Comment by AlexGyver** [comment]
Да, именно для этого есть isSingle, чтобы ловить один клик отдельно от двойного. В библиотеке не просто так много разных методов

**Comment by x3mEr** [comment]
Т. е. совет при использовании библиотеки: в программах, где планируется различать двойные и одинарные нажатия, лучше использовать только isSingle и isDouble, без isClick?

P.S.: хм, isClick можно было бы использовать в качестве флага "были ли какие-нибудь нажатия", но тогда её (bool isOne_f) надо сбрасывать и в других атрибутах, не только в isClick

**Comment by AlexGyver** [comment]
isClick легче и быстрее, если в программе нужна только отработка клика и удержания, то юзать isClick. А если множественные нажатия, то isSingle и его друзей. Также ещё есть isPress и release, которые тоже можно юзать. Но вообще есть над чем подумать, отделить флаг клика. Ещё есть вариант сделать тик булевым, и уже по нему отслеживать были ли изменения
