### ISSUE TITLE
Определение цвета PINK конфликтует с макросом PINK в Меге2560 в microLED

### ISSUE THREAD

**Issue by simik-ru** [AlexGyver/GyverLibs#22]
В Меге2560 PINK это указатель на регистр настройки одного из портов
![изображение](https://user-images.githubusercontent.com/11256172/70390507-c06ba100-19dc-11ea-947c-23bbe0537a14.png)

Его определение конфликтует с определением цвета PINK в microLED.h:113, из-за чего скетчи под Мегу не компилируются.

Как вариант переименовать цвет, допустим, в MAGENTA, как он и называется по мнению википедии
![изображение](https://user-images.githubusercontent.com/11256172/70390587-59022100-19dd-11ea-8ca6-4223ee27c61a.png)

**Comment by AlexGyver** [comment]
Принято, сейчас исправлю)
