### ISSUE TITLE
GyverTimer012

### ISSUE THREAD

**Issue by fordisimo** [AlexGyver/GyverLibs#23]
Dear Alex.
In the example to the library, only Timer1 is used.
Have you checked Timer2 and Timer0.
For some reason, only Timer1 works for me.

Request placed on your forum
https://community.alexgyver.ru/threads/problema-v-ispolzovanii-biblioteki-gyvertimer012.2166/

Look here please.
Teska.

Уважаемый, Алекс.
В примере к библеотеке использован только Timer1.
Проверяли ли Вы Timer2 and Timer0.
У меня почему то работает только Timer1.

Запрос поместил на Вашем форуме
https://community.alexgyver.ru/threads/problema-v-ispolzovanii-biblioteki-gyvertimer012.2166/

Посмотрите пожалуйста.
Теска.

**Comment by AlexGyver** [comment]
Для таймера 0 и 2
Максимальный период - 16384 мкс (соотв. частота 61 Гц)

**Comment by fordisimo** [comment]
Спасибо, причина именно в этом - использовал не недопустимое значение переменной.

**Comment by fordisimo** [comment]
Еще раз огромное спасибо за оперативную реакцию.
Александр.
