### ISSUE TITLE
TM1637. Не управляются точки на дисплее.

### ISSUE THREAD

**Issue by fordisimo** [AlexGyver/GyverLibs#24]
Суть проблемы : - Заменил дисплей с ":" по середине на дисплей с Десятичными точками.
- Обнаружил, что точки не управляются.
Просьба к авторам библиотеки рассмотреть проблему и добавить/расширить функции библиотеки.

Ниже привожу быстрое решение, которое из-за лимита времени применил. Оно справедливо только для функции point() и display().
Подчеркиваю, что с огромным уважение отношусь к авторам библиотеке и позволил себе внести изменения только из-за крайнего цейтнота.
(в файлах библиотеки отмечены строки, в которых произведены изменения).

Пример (все как для Оригинальной библиотеки + небольшие изменения):

#include <GorTM1637.h>

#define CLK A5 //pin-ы для TM1637
#define DIO A4

GorTM1637 disp(CLK, DIO);

void setup()
{
disp.clear(); // инициализация TM1637
disp.brightness(7); // ярк, 0 - 7 (минимум - максимум)
}

void loop()
{
disp.point(POINT_ON,2); // ТОЧКУ поставим во 2-ю поз. ( слева направо, начиная с нуля)

disp.displayInt(301); // получим па дисплее 30.1

delay(2000);

disp.point(POINT_OFF,2); // погасить точку (если надо)
disp.displayInt(103); // получим па дисплее 103

delay(2000);

}

Библиотека с модификациями в посте здесь https://community.alexgyver.ru/threads/biblioteka-dlja-tm1637-s-desjatichnoj-tochkoj.2249/

**Comment by AlexGyver** [comment]
а для какого дисплея возник вопрос? Можно ссылку?

**Comment by fordisimo** [comment]
Дисплей куплен в магазине,  контроллер ТМ 1637 (выдно на фото).
С уважением, Александр.
[image: TM1637_1.jpg]
[image: TM1637_2.jpg]
[image: TM1637_3.jpg]


пт, 21 лют. 2020 о 16:27 Alex <notifications@github.com> пише:

**Comment by AlexGyver** [comment]
не вижу фоток

**Comment by fordisimo** [comment]
а приатаченые файлы есть?

ср, 26 лют. 2020 о 00:56 Alex <notifications@github.com> пише:

**Comment by AlexGyver** [comment]
нету

**Comment by fordisimo** [comment]
так должно работать :)
https://drive.google.com/drive/folders/1B9COL8aOvwkxxeJFliNkD4Yy_FW9sLhr?usp=sharing

ср, 26 лют. 2020 о 18:37 Alex <notifications@github.com> пише:

**Comment by AlexGyver** [comment]
Поддержки такого дисплея в библиотеке нет. Можно ссылочку? Куплю себе

**Comment by fordisimo** [comment]
https://aliexpress.ru/item/32962489291.html?spm=a2g0s.9042311.0.0.1ce233edAsKNcl


чт, 27 лют. 2020 о 13:53 Alex <notifications@github.com> пише:

**Comment by AlexGyver** [comment]
Окей босс

**Comment by fordisimo** [comment]
🤔

пт, 28 лют. 2020 о 10:37 Alex <notifications@github.com> пише:

**Comment by fordisimo** [comment]
https://community.alexgyver.ru/threads/biblioteka-dlja-tm1637-s-desjatichnoj-tochkoj.2249/


тут я быстренько   слепил заплатку, глубоко не прорабатовал.

пн, 2 бер. 2020 о 10:16 Olexander Horoshko <fordisimo@gmail.com> пише:

**Comment by AlexGyver** [comment]
Окей, как приедет сделаю что нибудь приличное

**Comment by fordisimo** [comment]
удачи

вт, 3 бер. 2020 о 11:01 Alex <notifications@github.com> пише:

**Comment by Anymorf** [comment]
как там есть сподвижки по точкам?

**Comment by AlexGyver** [comment]
Не, нет времени

**Comment by AlexGyver** [comment]
Идёт разработка
