### ISSUE TITLE
Нельзя одновременно подключить GyverTimer и GyverHacks 

### ISSUE THREAD

**Issue by RadmirT** [AlexGyver/GyverLibs#25]
В обеих библиотеках объявляется класс GTimer.
Я попробовал удалил объявление класса и его тело из в библиотеки GyverHacks т.к.  судя по коду в GyverHacks это класс нигде не используется. 
Все собралось, но возникла проблема с таймерами в GyverTimer после вызова anyPWMinit они перестают работать.

**Comment by AlexGyver** [comment]
anyPWM очень сильно бьёт по производительности микроконтроллера, а также отбирает второй аппаратный таймер
