### ISSUE TITLE
Не правильно работает метод GLinear::compute  в библиотеке GyverFilters

### ISSUE THREAD

**Issue by Dimazay** [AlexGyver/GyverLibs#27]
Переменные **sumX, sumY, sumX2, sumXY** В классе GLinear не ресетятся в функции  GLinear::compute из за чего при её повторном (многократном) вызове результат неверный.

Нужно в файл **GyverFilters/GyverFilters.cpp** в метод  **GLinear::compute** после:
`arrSize /= sizeof(int);`

добавить:

```
sumX = 0;
sumY = 0;
sumX2 = 0;
sumXY = 0;
```

**Comment by AlexGyver** [comment]
Спасибо, справедливо! Внёс их в локальные, в классе они вообще не нужны
