### ISSUE TITLE
Не хватает функции в GyverButton

### ISSUE THREAD

**Issue by planer-pro** [AlexGyver/GyverLibs#29]
А конкретно функции, которая бы чистила все буфера butt.tick(); о захвате нажатия, а то в не зависимости нужно слушать в данный момент остальные кнопки помимо тех которые нужно, tick все запоминает в буфер а потом делает ложное срабатывание, когда остальным кнопкам уже разрешено реагировать, но ты еще ничего не нажимал. Пример с постраничным меню дисплея, на каждой странице разрешено читать свои кнопки, а не все сразу и писать в буфер что они тоже были нажаты - прочитал butt.isClick(); и сразу все буфера clear а еще лучше выбранные буфера.

**Comment by AlexGyver** [comment]
Данная фича была добавлена в версии 3.4, метод resetStates()

**Comment by planer-pro** [comment]
good!
