### ISSUE TITLE
Проблема с 

### ISSUE THREAD

**Issue by hyperion11** [AlexGyver/GyverLibs#3]
Проблема с энкодером.
Если просто кликать на кнопку то
1. не все нажатия отрабатываются.
2. ложное Holded (кнопка быстро отпускается)
3. Press-Holded просто чередуется. Хотя по факту были только нажатия
Подключен не через прерывания.
#define CLK 7
#define DT 8
#define SW 10
Encoder enc1(CLK, DT, SW);

Press
Holded
Press
Holded
Press
Holded
Press
Holded
Press
Holded
Press
Holded
Press
Holded
Press
Holded
Press
Holded
Press
Holded
Press
Holded
Press

**Comment by AlexGyver** [comment]
Попробуй скачать актуальную версию библиотеки, там много было переделано
