### ISSUE TITLE
GyverButton (и не только) оптимизация

### ISSUE THREAD

**Issue by alehano** [AlexGyver/GyverLibs#31]
Хочу предложить небольшую оптимизацию проверки нажатия.
Каждый раз в цикле проверяется разность во времени, но можно таймаут заранее прибавлять к переменной mills() и сравнивать текущее значение mills() со значением в будущем, если текущее больше, то таймаут прошел. 
Таким образом избавляемся от арифметической операции каждый тик и только сравниваем два числа. 

```
// обработка накликивания
	if ((thisMls - btn_timer >= _click_timeout) && (btn_counter != 0)) {    
		last_counter = btn_counter;
		btn_counter = 0;
		flags.counter_flag = true;
	}
```

Можно присваивать везде `btn_timer = thisMls + _click_timeout`
А потом проверять условие
`thisMls >= btn_timer`

**Comment by PetrakovKirill** [comment]
Допустим `thisMls = 0xFFFFFFF0, _click_timeout = 0x20`
тогда из `btn_timer = thisMls + _click_timeout` следует:
`btn_timer  = 0xFFFFFFF0 + 0x20 = 0x10`, так как будет переполнение.
Тогда выражение `thisMls >= btn_timer`, когда `thisMls = 0xFFFFFFF1`, будет `true`,
т.е. получаем ошибочное поведение.
