### ISSUE TITLE
Лента жарит яки чёрт

### ISSUE THREAD

**Issue by Crazy-Geeks** [AlexGyver/GyverLibs#35]
Atmega 32u4 (Pro Micro), полёт нормальный, но есть, как говорится, один нюанс. setMaxCurrent не работает. Ток стоит 500 мА -1А, лента выжигает глаза буквально, в FastLED при ограничении в 1А она еле светила
![image](https://user-images.githubusercontent.com/39135096/75613620-e36fa200-5b40-11ea-9852-02251a93cfd2.png)
![image](https://user-images.githubusercontent.com/39135096/75613683-9e983b00-5b41-11ea-8579-189bb4971b5e.png)
(Через камеру не передашь, естественно)

**Comment by AlexGyver** [comment]
А что за лента? По моим тестам ограничение тока работало прям плюс минус пара миллиампер. Но ленты разные...

**Comment by Crazy-Geeks** [comment]
WS2812B, у giant4 брал
Камень 32u4 16 mhz
Такое ощущение, что эта функция вообще игнорируется, при изменении значений яркость так и остаётся 
У FastLED то оно работает, поэтому проблемы не с лентой

**Comment by AlexGyver** [comment]
А какая версия либы? И ты ток измерял, или чисто визуально?

**Comment by AlexGyver** [comment]
Библиотека обновлена
