### ISSUE TITLE
Использование библиотеки для второго uart 

### ISSUE THREAD

**Issue by alexAntonovMsk** [AlexGyver/GyverLibs#38]
Не нашел как можно использовать библиотеку для второго uart порта в ардуино?
У меня плата икра нано про, там есть второй порт

**Comment by AlexGyver** [comment]
На твоей плате стоит ATmega328PB, новая версия 328 микроконтроллера. В данной библиотеке нет поддержки этого процессора и нескольких юартов в принципе
