### ISSUE TITLE
Неожиданное поведение методов isPress и isRelease при зажатии кнопки энкодера.

### ISSUE THREAD

**Issue by kostyamat** [AlexGyver/GyverLibs#39]
Вот такой код
```
  if (enc1.isPress()) {           // Если кнопку нажали.
    digitalWrite(swich, 0);
  }
  if (enc1.isRelease()) {         // Если кнопку отпустили. Таким способом хоть зажимай кнопку, хоть кликай, это должно бы повторять действия пользователя.
    digitalWrite(swich, 1);
  }
```
работает неожиданно, а точнее как тригер, если кнопку нажимать не кратко, а зажать. 
При этом короткие нажатия отрабатываются как надо. Похоже методы isPress и isRelease перестают работать должным образом, когда истекает таймаут для isHolded. Сами же методы isHold и isHolded в данной задаче не применимы, контроллер просто должен повторять действия пользователя. Или я чего-то не понял?
Может ли быть заменой ```digitalWrite(swich, !enc1.isHold);```

**Comment by AlexGyver** [comment]
В версии v4.6 добавил isReleaseHold, будет делать ровно то что тебе нужно
