### ISSUE TITLE
Неправильная конвертация цвета из HSV в RGB

### ISSUE THREAD

**Issue by VICLER** [AlexGyver/GyverLibs#40]
метод LEDdata mHSV(byte h, byte s, byte v) при аргументах h = 180, s = 255, v = 255 выдаёт 
R = 60, G = 0, B = 255
a должен выдавать R = 0, G = 255, B = 255

**Comment by AlexGyver** [comment]
Не должен, в данной библиотеке используется вот такой алгоритм преобразования:
![Скриншот 22-05-2020 195759](https://user-images.githubusercontent.com/21090953/82691428-8e868800-9c66-11ea-9435-1f9859fd91e1.jpg)
