### ISSUE TITLE
Вызов ServoSmooth::write (writeUs) должен обновлять _servoCurrentPos

### ISSUE THREAD

**Issue by CheDima** [AlexGyver/GyverLibs#41]
https://github.com/AlexGyver/GyverLibs/blob/cdd8330751167f4f24384f8f228d962dee956879/ServoSmooth/ServoSmooth.cpp#L14

Иначе при первом tick (вызванном после write) сначала происходит рывок к позиции _servoCurrentPos (уже неправильной)

**Comment by AlexGyver** [comment]
Вот в таком виде сделать? 
```
void ServoSmooth::writeUs(int val) {
	_servo.writeMicroseconds(_dir ? (_max - val) : val);
	_servoCurrentPos = val;
}
```
Ты тестировал такой вариант?

**Comment by AlexGyver** [comment]
Сделал в общем в 2.2
