### ISSUE TITLE
Объекты медианного фильтра имеют общие переменные

### ISSUE THREAD

**Issue by DmitryBorisenko33** [AlexGyver/GyverLibs#42]
Я использую медианный фильтр и создаю два отдельных объекта что бы фильтровать две отдельные переменные. Но переменные преравниваются одна к другой.

Вот так я объявил два объекта:

```
#include "GyverFilters.h"
GMedian medianFilter1;
GMedian medianFilter2;

```
Вот так я фильтрую переменные:

```
if (json_key_buf == "vgi") {

      int16_t date1 = current_date;
      date1 = medianFilter1.filtered(date1);
      jsonWriteInt(inv001, json_key_buf, date1);

    } else if (json_key_buf == "vi") {

      int16_t date2 = current_date;
      date2 = medianFilter2.filtered(date2);
      jsonWriteInt(inv001, json_key_buf, date2);

    } else {
      jsonWriteInt(inv001, json_key_buf, current_date);
    }
```

На выходе я получаю объединение величин date1 и date2 

Точнее date2 равна date1 постоянно. 

Благодарю Вас за библиотеки и за Ваш сайт.

**Comment by AlexGyver** [comment]
Спасибо за багрепорт! Библиотека обновлена до версии 2.0, косяк с переменными исправлен, сам алгоритм оптимизирован и теперь фильтр объявляется вот таким образом
`GMedian<10, int> testFilter; `
Указывается его размер и тип данных
