### ISSUE TITLE
Неопределённое поведение в функциях `timer0_setPeriod` и `timer2_setPeriod`

### ISSUE THREAD

**Issue by ilyavennik** [AlexGyver/GyverLibs#52]
Рассмотрим параметры `time` функций [timer0_setPeriod](https://github.com/AlexGyver/GyverLibs/blob/bab4a7ca4cbcdb649e920a7776e5fd09e5773411/GyverTimer012/GyverTimer0.cpp#L11) и [timer2_setPeriod](https://github.com/AlexGyver/GyverLibs/blob/bab4a7ca4cbcdb649e920a7776e5fd09e5773411/GyverTimer012/GyverTimer2.cpp#L11). Так как каскад `if-else...` не обрабатывает все возможные значения аргумента `time` (пример из `timer0_setPeriod`):
```cpp
if (time > 1 && time <= 16) {
    divisor = 1;
    divValue = 1;
} else if (time > 16 && time <= 128) {
    divisor = 8;
    divValue = 2;
} else if (time > 128 && time <= 1024) {
    divisor = 32;
    divValue = 3;
} else if (time > 1024 && time <= 4096) {
    divisor = 64;
    divValue = 4;
} else if (time > 4096 && time <= 16384) {
    divisor = 128;
    divValue = 5;
} else TCCR0B = 1;
```
то для любых значений `time` больше `16384` на следующей строке произойдёт чтение не инициализированной переменной `divisor`:
https://github.com/AlexGyver/GyverLibs/blob/bab4a7ca4cbcdb649e920a7776e5fd09e5773411/GyverTimer012/GyverTimer0.cpp#L38
и
https://github.com/AlexGyver/GyverLibs/blob/bab4a7ca4cbcdb649e920a7776e5fd09e5773411/GyverTimer012/GyverTimer2.cpp#L44

P.S. Изменение типа параметра на `uint16_t` нарушит обратную совместимость.

**Comment by AlexGyver** [comment]
Библиотека устарела и не используется/не обновляется

**Comment by ilyavennik** [comment]
В таком случае её нужно либо удалить, либо пометить устаревшей явно.

**Comment by AlexGyver** [comment]
Вроде пометил как мог

**Comment by ilyavennik** [comment]
Ни в README, ни в коде таких пометок не нашёл.

**Comment by AlexGyver** [comment]
![Screenshot_2020-11-01-21-25-54-016_com android chrome](https://user-images.githubusercontent.com/21090953/97811020-e222e600-1c88-11eb-941e-a09ff5b72d7e.jpg)

**Comment by AlexGyver** [comment]
Библиотека устарела
