### ISSUE TITLE
Поддержка ESP8266

### ISSUE THREAD

**Issue by Mostalk** [AlexGyver/GyverLibs#64]
Alex, добавь пожалуйста поддежку ESP8266 в свои библиотеки

**Comment by AlexGyver** [comment]
Все библиотеки написаны для экосистемы Ардуино и большинство без проблем работают на ESP. Если что-то не работает - все вопросы к компилятору ESP =) А также к описанию конкретной библиотеки, часть из них написана конкретно под архитектуру AVR и под ESP их переделать в принципе невозможно.
