### ISSUE TITLE
Поддержка BMP280 в библиотеке BME280

### ISSUE THREAD

**Issue by Toptijka** [AlexGyver/GyverLibs#68]
Если не трудно разрешите в либе использовать BMP вместо BME.

Собственно при проверке id разрешить значение 0х58. Адреса/формат регистров практические не меняются. Только отсутствуют регистры контроля и данных влажности.

**Comment by Toptijka** [comment]
В дополнение то есть.

**Comment by AlexGyver** [comment]
Ведётся разработка
