### ISSUE TITLE
Ошибки компиляции

### ISSUE THREAD

**Issue by Kabron287** [AlexGyver/GyverLibs#69]
`D:\Arduino\libraries\GyverPower\GyverPower.cpp: In member function 'uint8_t GyverPower::sleepDelay(uint32_t)':
D:\Arduino\libraries\GyverPower\GyverPower.cpp:159:11: error: invalid conversion from 'uint8_t {aka unsigned char}' to 'sleepprds_t' [-fpermissive]
    sleep(i);        // уйти в сон`

**Comment by AlexGyver** [comment]
Поправил, спасибо
