### ISSUE TITLE
При компиляции в Eclipse, возникает ошибка GyverFilters.cpp:29:1: error: control reaches end of non-void function [-Werror=return-type]

### ISSUE THREAD

**Issue by kang2k10** [AlexGyver/GyverLibs#70]
При компиляции в Eclipse, возникает ошибка GyverFilters.cpp:29:1: error: control reaches end of non-void function [-Werror=return-type]

Насколько я понимаю, это из за того, что функция GFilterRA::filteredTime возвращает значение только после того как пройдет заданное время....

**Comment by AlexGyver** [comment]
Исправил, спасибо
