### ISSUE TITLE
GyverOLED [dev] -> setCursor - странное поведение

### ISSUE THREAD

**Issue by linotex** [AlexGyver/GyverLibs#76]
Привет!
Странно, но почему-то setCursor устанавливает позицию символа только для **y**, а для **x** попиксельно. Так было задумано или просто копипаста?

**Comment by AlexGyver** [comment]
Привет, копипаста откуда? Так было задумано, потому что олед аппаратно адресует столбики по 8 байт, что активно используется для работы без буфера. Если нужно ткнуть точно в Y - используй setCursorXY

**Comment by linotex** [comment]
Но если я хочу установить курсор на 5 столбец и 4 строку мне нужно сделать `setCursor(5 << 3, 4)` или туплю?

**Comment by AlexGyver** [comment]
Просто 5, зачем << 3? Откуда эта копипаста?)

**Comment by linotex** [comment]
Если просто 5 то устанавливаеться в 5 пиксель, не в столбец ((. Возможно что то не так инициализирую. Код взял с метода setCursor

Там даже в коментарии указано пиксели по x
```
	// поставить курсор для символа 0-127, 0-8(4)
	void setCursor(int x, int y) { setCursorXY(x, y << 3); }
```

**Comment by AlexGyver** [comment]
а что в твоём понимании столбец? Если столбец текста, то символ имеет ширину 6 пикселей, то есть просто умножай x на 6

**Comment by linotex** [comment]
Для меня столбец 8 пикселей
Я делал меню для своего проекта и сделал курсор символом `>` и мне нужно было переместить курсор дальше и нарисовать иконку а потом и текст (да да, я знаю при печати оно автоматически двигает курсор). И посколько `setCursor` двигает курсор на 8 пикселей, то я решил что также должно двигать на 8 пикселей по x и для меня было странно что это не так. Потому и задал вопрос :) Но тепер понял что так было задумано ))
