### ISSUE TITLE
Режим KEEP_SPEED - не адекватно работают ускорения

### ISSUE THREAD

**Issue by AlexCrane73** [AlexGyver/GyverLibs#78]
В режиме KEEP_SPEED не работает плавная остановка шагового двигателя при вызове stop (пробовал тестовый скетч).
Так-же если в режиме KEEP_SPEED при плавном наборе скорости вызвать stop() и затем опять включить вращение то вращение начнется с не нулевой скорости, а с момента когда вызвали stop т.е. может сразу рвануть без ускорения.

**Comment by AlexGyver** [comment]
всё починил в свежем обновлении, спасибо!!!
